Attribute VB_Name = "mAPIs"
Public Function real_api(a_number As Integer) As String
Dim sApi(60) As String

sApi(1) = "Private Declare Function %RANDOM% Lib  & Chr(34) & gdi32 & Chr(34) &  (ByVal hDC As Long) As Long"
sApi(2) = "Private Declare Function %RANDOM% Lib  & Chr(34) & gdi32 & Chr(34) &  (ByVal hDC As Long) As Long"
sApi(3) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  (ByVal hCursor As Long) As Long"
sApi(4) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  (ByVal hDC As Long, ByVal xLeft As Long, ByVal yTop As Long, ByVal hIcon As Long, ByVal OutputWidth As Long, ByVal OutputHeight As Long, ByVal iStepIfAniCur As Long, ByVal hbrFlickerFreeDraw As Long, ByVal diFlags As Long) As Long"
sApi(5) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  Alias  & Chr(34) & LoadCursorFromFileA & Chr(34) &  (ByVal lpFileName As String) As Long"
sApi(6) = "Private Declare Function %RANDOM% Lib  & Chr(34) & olepro32.dll & Chr(34) &  (ByVal OLE_COLOR As Long, ByVal hPalette As Long, lpColorRef As Long) As Long"
sApi(7) = "Private Declare Function %RANDOM% Lib  & Chr(34) & WINMM.DLL & Chr(34) &  Alias  & Chr(34) & mciGetErrorStringA & Chr(34) &  (ByVal ErrorNumber As Long, ByVal ReturnBuffer As String, ByVal ReturnBufferSize As Long) As Long 'BOOL"
sApi(8) = "Private Declare Function %RANDOM% Lib  & Chr(34) & WINMM.DLL & Chr(34) &  Alias  & Chr(34) & mciSendStringA & Chr(34) &  (ByVal CommandString As String, ByVal ReturnBuffer As String, ByVal ReturnBufferSize As Long, ByVal hCallback As Long) As Long 'MCIERROR"
sApi(9) = "Private Declare Function %RANDOM% Lib  & Chr(34) & WINMM.DLL & Chr(34) &  Alias  & Chr(34) & mmioInstallIOProcA & Chr(34) &  (ByVal fccIOProc As Long, ByVal pIOProc As Long, ByVal dwFlags As Long) As Long"
sApi(10) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  Alias  & Chr(34) & GetWindowTextA & Chr(34) &  (ByVal hWnd As Long, ByVal strText As String, ByVal TextLength As Long) As Long"
sApi(11) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  Alias  & Chr(34) & SetWindowTextA & Chr(34) &  (ByVal hWnd As Long, ByVal strText As String) As Long"
sApi(12) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  Alias  & Chr(34) & FindWindowA & Chr(34) &  (ByVal lpClassName As String, ByVal lpWindowName As String) As Long"
sApi(13) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  (ByVal hWnd As Long, lpRect As Long) As Long"
sApi(14) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  Alias  & Chr(34) & SetWindowTextA & Chr(34) &  (ByVal hWnd As Long, ByVal LPString As String) As Long"
sApi(15) = "Private Declare Function %RANDOM% Lib  & Chr(34) & WINMM.DLL & Chr(34) &  Alias  & Chr(34) & mciSendStringA & Chr(34) &  (ByVal lpstrCommand As String, ByVal lpstrReturnString As String, ByVal uReturnLength As Long, ByVal hwndCallback As Long) As Long"
sApi(16) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  (ByVal hWnd As Long, ByVal X As Long, ByVal Y As Long, ByVal nWidth As Long, ByVal nHeight As Long, ByVal bRepaint As Long) As Long"
sApi(17) = "Private Declare Function %RANDOM% Lib  & Chr(34) & WINMM.DLL & Chr(34) &  (ByVal hMixer As Long) As Long"
sApi(18) = "Private Declare Function %RANDOM% Lib  & Chr(34) & WINMM.DLL & Chr(34) &  Alias  & Chr(34) & mixerGetLineControlsA & Chr(34) &  (ByVal hMixerObj As Long, pMixerLc As long, ByVal fdwControls As Long) As Long"
sApi(19) = "Private Declare Function %RANDOM% Lib  & Chr(34) & WINMM.DLL & Chr(34) &  Alias  & Chr(34) & mixerGetLineInfoA & Chr(34) &  (ByVal hMixerObj As Long, pMixerL As long, ByVal fdwInfo As Long) As Long"
sApi(20) = "Private Declare Function %RANDOM% Lib  & Chr(34) & WINMM.DLL & Chr(34) &  (ByRef phMixer As Long, ByVal uMxId As Long, ByVal dwCallback As Long, ByVal dwInstance As Long, ByVal fdwOpen As Long) As Long"
sApi(21) = "Private Declare Function %RANDOM% Lib  & Chr(34) & WINMM.DLL & Chr(34) &  (ByVal hMixerObj As Long, pMixerCD As long, ByVal fdwDetails As Long) As Long"
sApi(22) = "Private Declare Function %RANDOM% Lib  & Chr(34) & gdi32 & Chr(34) &  (ByVal hColorSpace As Long) As Long"
sApi(23) = "Private Declare Function %RANDOM% Lib  & Chr(34) & gdi32 & Chr(34) &  (ByVal hDC As Long) As Long"
sApi(24) = "Private Declare Function %RANDOM% Lib  & Chr(34) & gdi32 & Chr(34) &  (ByVal hEnhMetaFile As Long) As Long"
sApi(25) = "Private Declare Function %RANDOM% Lib  & Chr(34) & gdi32 & Chr(34) &  (ByVal hMetaFile As Long) As Long"
sApi(26) = "Private Declare Function %RANDOM% Lib  & Chr(34) & gdi32 & Chr(34) &  (ByVal hGDIObj As Long) As Long"
sApi(27) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  (ByVal hCursor As Long) As Long"
sApi(28) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  (ByVal hIcon As Long) As Long"
sApi(29) = "Private Declare Function %RANDOM% Lib  & Chr(34) & gdi32 & Chr(34) &  (ByVal hGdiObject As Long) As Long"
sApi(30) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  (ByVal IconOrCursor As Long, ByRef pICONINFO As Long) As Long"
sApi(31) = "Private Declare Function %RANDOM% Lib  & Chr(34) & olepro32.dll & Chr(34) &  (ByRef PicDesc As Any, ByRef RefIID As Long, ByVal fPictureOwnsHandle As Long, ByRef IPic As long) As Long"
sApi(32) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  Alias  & Chr(34) & LoadBitmapA & Chr(34) &  (ByVal hInstance As Long, ByVal lngBitmapID As Long) As Long"
sApi(33) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  Alias  & Chr(34) & LoadCursorA & Chr(34) &  (ByVal hLib As Long, ByVal lngCursorID As Long) As Long"
sApi(34) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  Alias  & Chr(34) & LoadIconA & Chr(34) &  (ByVal hLib As Long, ByVal lngIconID As Long) As Long"
sApi(35) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  Alias  & Chr(34) & LoadStringA & Chr(34) &  (ByVal hLib As Long, ByVal ResourceID As Long, ByVal lpBuffer As String, ByVal nBufferSize As Long) As Long"
sApi(36) = "Private Declare Function %RANDOM% Lib  & Chr(34) & WINMM.DLL & Chr(34) &  Alias  & Chr(34) & sndPlaySoundA & Chr(34) &  (ByVal Sound As Long, ByVal lngFlags As Long) As Long"
sApi(37) = "Private Declare Function %RANDOM% Lib  & Chr(34) & SHELL32.DLL & Chr(34) &  Alias  & Chr(34) & SHGetFileInfoA & Chr(34) &  (ByVal pszPath As String, ByVal dwFileAttributes As Long, psfi As Long, ByVal cbFileInfo As Long, ByVal uFlags As Long) As Long"
sApi(38) = "Private Declare Function %RANDOM% Lib  & Chr(34) & version.dll & Chr(34) &  Alias  & Chr(34) & VerQueryValueA & Chr(34) &  (pBlock As Any, ByVal lpSubBlock As String, lplpBuffer As Any, puLen As Long) As Long"
sApi(39) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  (ByVal hDC As Long, ByVal X As Long, ByVal Y As Long, ByVal hIcon As Long) As Long"
sApi(40) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  (ByVal hIcon As Long) As Long"
sApi(41) = "Private Declare Function %RANDOM% Lib  & Chr(34) & version.dll & Chr(34) &  Alias  & Chr(34) & GetFileVersionInfoA & Chr(34) &  (ByVal lptstrFilename As String, ByVal dwHandle As Long, ByVal dwLen As Long, lpData As Any) As Long"
sApi(42) = "Private Declare Function %RANDOM% Lib  & Chr(34) & version.dll & Chr(34) &  Alias  & Chr(34) & GetFileVersionInfoSizeA & Chr(34) &  (ByVal lptstrFilename As String, lpdwHandle As Long) As Long"
sApi(43) = "Private Declare Function %RANDOM% Lib  & Chr(34) & gdi32 & Chr(34) &  (ByVal hDC As Long) As Long"
sApi(44) = "Private Declare Function %RANDOM% Lib  & Chr(34) & gdi32 & Chr(34) &  (ByVal hDC As Long) As Long"
sApi(45) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  (ByVal hCursor As Long) As Long"
sApi(46) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  (ByVal hDC As Long, ByVal xLeft As Long, ByVal yTop As Long, ByVal hIcon As Long, ByVal OutputWidth As Long, ByVal OutputHeight As Long, ByVal iStepIfAniCur As Long, ByVal hbrFlickerFreeDraw As Long, ByVal diFlags As Long) As Long"
sApi(47) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  Alias  & Chr(34) & LoadCursorFromFileA & Chr(34) &  (ByVal lpFileName As String) As Long"
sApi(48) = "Private Declare Function %RANDOM% Lib  & Chr(34) & olepro32.dll & Chr(34) &  (ByVal OLE_COLOR As Long, ByVal hPalette As Long, lpColorRef As Long) As Long"
sApi(49) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  Alias  & Chr(34) & SetWindowLongA & Chr(34) &  (ByVal hWnd As Long, ByVal nIndex As Long, ByVal dwNewLong As Long) As Long"
sApi(50) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  Alias  & Chr(34) & RegisterWindowMessageA & Chr(34) &  (ByVal LPString As String) As Long"
sApi(51) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32 & Chr(34) &  (ByVal nIndex As Long) As Long"
sApi(52) = "Private Declare Function %RANDOM% Lib  & Chr(34) & GDI32.DLL & Chr(34) &  (ByVal hDC As Long, ByVal nIndex As Long) As Long"
sApi(53) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32.DLL & Chr(34) &  Alias  & Chr(34) & SystemParametersInfoA & Chr(34) &  (ByVal uAction As Long, ByVal uParam As Long, ByRef lpvParam As Any, ByVal fuWinIni As Long) As Long"
sApi(54) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32.DLL & Chr(34) &  (ByVal hwndParent As Long, ByVal lpEnumCallback As Long, ByVal lParam As Long) As Long"
sApi(55) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32.DLL & Chr(34) &  Alias  & Chr(34) & GetClassNameA & Chr(34) &  (ByVal hWnd As Long, ByVal ClassName As String, ByVal ClassNameSize As Long) As Long"
sApi(56) = "Private Declare Function %RANDOM% Lib  & Chr(34) & USER32.DLL & Chr(34) &  (ByVal hWnd As Long) As Long"
sApi(57) = "Private Declare Function %RANDOM% Lib  & Chr(34) & winmm.dll & Chr(34) &  () As Long"
sApi(58) = "Private Declare Function %RANDOM% Lib  & Chr(34) & winmm.dll & Chr(34) &  (ByVal uPeriod As Long) As Long"
sApi(59) = "Private Declare Function %RANDOM% Lib  & Chr(34) & winmm.dll & Chr(34) &  (ByVal uPeriod As Long) As Long"
sApi(60) = "Private Declare Function %RANDOM% Lib  & Chr(34) & STKIT432.DLL & Chr(34) &  (ByVal lpstrFolderName As String, ByVal lpstrLinkName As String, ByVal lpstrLinkPath As String, ByVal lpstrLinkArgs As String) As Long"

Randomize
real_api = Replace(Replace(sApi(a_number), "%RANDOM%", GenNumKey(25)), " & Chr(34) & ", Chr(34))

Sleep (100)

End Function
